<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>TeklaDrawingAssistant</AssemblyName>
    <RootNamespace>TeklaDrawingAssistant</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <TeklaInstallDir Condition="'$(TeklaInstallDir)' == ''">C:\Program Files\Tekla Structures\2023.0\bin</TeklaInstallDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Tekla.Structures">
      <HintPath>$(TeklaInstallDir)\Tekla.Structures.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Tekla.Structures.Model">
      <HintPath>$(TeklaInstallDir)\Tekla.Structures.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Tekla.Structures.Drawing">
      <HintPath>$(TeklaInstallDir)\Tekla.Structures.Drawing.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
